export { default as academicService } from '@services/academicService';
export * from '@services/academicService';
export { default as apiClient } from '@services/apiClient';
export * from '@services/apiClient';
export { default as authService } from '@services/authService';
export * from '@services/authService';
export { default as onboardingService } from '@services/onboardingService';
export * from '@services/onboardingService';
export { default as superAdminService } from '@services/superAdminService';
export * from '@services/superAdminService';
